### ISSUE TITLE
[Suggestion] Make armature the parent of the meshes

### ISSUE THREAD

**Issue by Darkblader24** [iCyP/VRM_IMPORTER#9]
It is standard in Blender importers to make all meshes that belong to the armature children of the armature. So if you could do that during import, that would be awesome!

So instead of this: https://i.imgur.com/HOCESoh.png
make it like this: https://i.imgur.com/hjESM7r.png

Thanks!

**Comment by iCyP** [comment]
In import, I think to follow structure that glb(VRM) scene defines. 
So if mesh node be not child of skelton in glb(VRM), mesh is not parenting to armature.
When change structure of model in import, it will confuse export.

However. mesh that child of skelton is not parenting in IO now. This is issue. I want to fix it.

Thank you.

**Comment by iCyP** [comment]
This rep is not code page sorry.
